My First Program

1. Print

In [4]:
print ("I love neco")

cat ("\nR", "Program")

[1] "I love neco"

R Program

2. Variables and Data Types

In [8]:
myString <- "I Love R Programming"
wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE


print (myString)

class(myString)
class(wholeNum)
class(floatingNum)
class(isBool)

[1] "I Love R Programming"

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. Numerical Operators

In [12]:
x <- 10
y <- 3


add <- x + y
sub <- x - y
mul <- x * y
div <- x / y
mod <- x %% y
exp <- x ^ y

print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(exp)

[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1
[1] 1000

4. User Input

In [14]:
name <- readline("Enter name: ")

cat("Welcome to R Programming: ", name)

Enter name: gilly beng
Welcome to R Programming:  gilly beng

5. Decision Making

In [15]:
grade <- 88

if (grade < 75 ){
  print ("Failed")
}else{
  print ("Passed")
}

[1] "Passed"

6. Loop

In [16]:
for (i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Functions

In [17]:
addnumber <- function(a, b){
  return(a+b)
}

addnumber(3,7)

[1] 10

8. Vectors

In [20]:
grades <- c(98, 89, 91, 88, 96)

grades

cat ("MEAN: " ,mean(grades))
cat ("\nMAX: ",max(grades))
cat ("\nMIN: ",min(grades))
cat ("\nLENGTH: ",length(grades))
cat ("\nMEDIAN: ",median(grades))
cat ("\nSUMMARY: ",summary(grades))
summary(grades)

[1] 98 89 91 88 96

MEAN:  92.4
MAX:  98
MIN:  88
LENGTH:  5
MEDIAN:  91
SUMMARY:  88 89 91 92.4 96 98

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   88.0    89.0    91.0    92.4    96.0    98.0

9. Matrices

In [22]:
A <- matrix(c(1,2,3,4,5,6),nrow=2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

10. Lists

In [23]:
students <- list(
  name = "lynlyn",
  course = "BSCS",
  grade = 85
)

students

$name
[1] "lynlyn"

$course
[1] "BSCS"

$grade
[1] 85

11. Dataframe

In [24]:
students <- data.frame(
  name = c("lynlyn", "neco", "gill"),
  course = c("BSCS", "BSIT", "BSA"),
  grade = c(85, 99, 95)
)

students

  name   course grade
1 lynlyn BSCS   85
2 neco   BSIT   99
3 gill   BSA    95

12. Write to CCSV

In [25]:
#save dataframe to csv file

write.csv(students, "students.csv")

13. Read CSV File

In [27]:
data <- read.csv("students.csv")

head(data)
summary(data)

  X name   course grade
1 1 lynlyn BSCS   85
2 2 neco   BSIT   99
3 3 gill   BSA    95

       X              name         course      grade
 Min.   :1.0   Length   :3   Length   :3   Min.   :85
 1st Qu.:1.5   N.unique :3   N.unique :3   1st Qu.:90
 Median :2.0   N.blank  :0   N.blank  :0   Median :95
 Mean   :2.0   Min.nchar:4   Min.nchar:3   Mean   :93
 3rd Qu.:2.5   Max.nchar:6   Max.nchar:4   3rd Qu.:97
 Max.   :3.0                               Max.   :99

14.